# Generated by Django 2.2.7 on 2019-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191224_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='reg_pizza_type',
            field=models.CharField(default='Special', max_length=65),
            preserve_default=False,
        ),
    ]
