# Generated by Django 2.2.7 on 2019-11-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='PastaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PlatterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SaladType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='orders.FoodSize')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='orders.SubType')),
                ('toppings', models.ManyToManyField(blank=True, related_name='sub', to='orders.SubTopping')),
            ],
        ),
        migrations.CreateModel(
            name='SaladOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salad', to='orders.SaladType')),
            ],
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platter', to='orders.FoodSize')),
                ('platter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='orders.PlatterType')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.FoodSize')),
                ('pizza_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='orders.PizzaType')),
                ('toppings', models.ManyToManyField(blank=True, related_name='pizza', to='orders.PizzaTopping')),
            ],
        ),
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta', to='orders.PastaType')),
            ],
        ),
    ]
