# Generated by Django 2.2.7 on 2019-11-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatoppings',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtoppings',
            name='name',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
