# Generated by Django 2.2.7 on 2019-11-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191120_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzatoppings',
            old_name='toppin',
            new_name='topping',
        ),
    ]
