# Generated by Django 2.2.7 on 2019-12-24 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191127_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastaorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Complete', 'Complete')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Complete', 'Complete')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platterorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Complete', 'Complete')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saladorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Complete', 'Complete')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Complete', 'Complete')], default='Draft', max_length=20),
            preserve_default=False,
        ),
    ]
