# Generated by Django 2.2.7 on 2019-11-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191120_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Pizzas',
        ),
        migrations.RenameField(
            model_name='pizzatoppings',
            old_name='topping',
            new_name='pizzas',
        ),
        migrations.RenameField(
            model_name='subtoppings',
            old_name='topping',
            new_name='subs',
        ),
    ]
