# Generated by Django 2.2.7 on 2019-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191120_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(max_length=64)),
                ('pizza_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pizzas', models.ManyToManyField(blank=True, related_name='topping', to='orders.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platter_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('subs', models.ManyToManyField(blank=True, related_name='topping', to='orders.Sub')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizzatoppings',
            name='pizzas',
        ),
        migrations.DeleteModel(
            name='Platters',
        ),
        migrations.RemoveField(
            model_name='subtoppings',
            name='subs',
        ),
        migrations.DeleteModel(
            name='Pizzas',
        ),
        migrations.DeleteModel(
            name='PizzaToppings',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
        migrations.DeleteModel(
            name='SubToppings',
        ),
    ]
