# Generated by Django 2.2.7 on 2019-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191120_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=65)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='foodsize',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='orders.FoodSize'),
        ),
        migrations.AddField(
            model_name='sub',
            name='foodsize',
            field=models.ManyToManyField(blank=True, related_name='sub', to='orders.FoodSize'),
        ),
    ]
