# Generated by Django 2.2.7 on 2019-11-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191120_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_size',
        ),
    ]
